-- Seed 004 | drone_routes
--
-- SIMULATION / DEVELOPMENT DATA.
--
-- These are deliberately COARSE three-point placeholder paths, not road
-- geometry. Each is a straight-ish line across one patrol zone, generated by
-- evenly dividing the corridor between the approximate Krishnagiri and Hosur
-- coordinates. They exist so the schema, repositories and API can be exercised
-- before Phase 3 imports real OpenStreetMap highway geometry.
--
-- Nothing here should be presented as an actual flight path.
--
-- zone_id is filled in by seed 005, once the zones exist.
-- distance_meters is computed by MySQL from the geometry at the end of this
-- file, so no distance value is ever hand-entered.
--
-- Geometry convention: WKT longitude-first, parsed with 'axis-order=long-lat'.

INSERT INTO drone_routes (id, name, route_type, geometry, status, data_source)
VALUES
  (1, 'Patrol Route 01 - Krishnagiri sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.210 12.520, 78.191 12.531, 78.172 12.542)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (2, 'Patrol Route 02 - Krishnagiri sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.172 12.542, 78.153 12.553, 78.134 12.564)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (3, 'Patrol Route 03 - Kundarapalli sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.134 12.564, 78.115 12.575, 78.096 12.586)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (4, 'Patrol Route 04 - Kundarapalli sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.096 12.586, 78.077 12.597, 78.058 12.608)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (5, 'Patrol Route 05 - Kurubarapalli sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.058 12.608, 78.039 12.619, 78.020 12.630)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (6, 'Patrol Route 06 - Kurubarapalli sector', 'PATROL',
   ST_GeomFromText('LINESTRING(78.020 12.630, 78.001 12.641, 77.982 12.652)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (7, 'Patrol Route 07 - Shoolagiri sector', 'PATROL',
   ST_GeomFromText('LINESTRING(77.982 12.652, 77.963 12.663, 77.944 12.674)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (8, 'Patrol Route 08 - Shoolagiri sector', 'PATROL',
   ST_GeomFromText('LINESTRING(77.944 12.674, 77.925 12.685, 77.906 12.696)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (9, 'Patrol Route 09 - Hosur sector', 'PATROL',
   ST_GeomFromText('LINESTRING(77.906 12.696, 77.887 12.707, 77.868 12.718)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED'),
  (10, 'Patrol Route 10 - Hosur sector', 'PATROL',
   ST_GeomFromText('LINESTRING(77.868 12.718, 77.849 12.729, 77.830 12.740)', 4326, 'axis-order=long-lat'),
   'ACTIVE', 'SIMULATED');

-- Distance in metres, computed by MySQL on the geographic SRS.
UPDATE drone_routes
SET distance_meters = ROUND(ST_Length(geometry), 2);
